"""Constants in the Viber network."""

MAX_PICTURE_DESCRIPTION_LENGTH = 120
MAX_PICTURE_SIZE = int(1E6)  # (1MB)
MAX_THUMBNAIL_SIZE = int(1E5)  # (100KB)
MAX_TRACKING_DATA_LENGTH = 4000
MAX_VIDEO_SIZE = int(50E6)  # 50MB
MAX_FILE_SIZE = int(50E6)  # 50MB
MAX_VIDEO_DURATION = 180  # 180 seconds
MAX_FILE_NAME_LENGTH = 256
MAX_URL_LENGTH = 2000

# constants above this line are tested

# SUPPORTED_WEBHOOK_PORTS = [443, 80, 88, 8443]
# MAX_FILESIZE_DOWNLOAD = int(20E6)  # (20MB)
# MAX_FILESIZE_UPLOAD = int(50E6)  # (50MB)
# MAX_MESSAGES_PER_SECOND_PER_CHAT = 1
# MAX_MESSAGES_PER_SECOND = 30
# MAX_MESSAGES_PER_MINUTE_PER_GROUP = 20
# MAX_MESSAGE_ENTITIES = 100
# MAX_INLINE_QUERY_RESULTS = 50
